# Generated by Django 5.0.6 on 2026-08-26 17:41

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=20, unique=True, validators=[apps.accounts.validators.validate_egyptian_phone]),
        ),
    ]
